[package]
name = "gtfs-realtime-benches-1"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
gtfs-realtime = "0.1.0"
prost = "0.13.1"
quick-protobuf = "0.8.1"
reqwest = "0.12.5"
tokio = { version = "1.39.2", features = ["full"] }
wyhash2 = "0.2.1"
